# Generated by Django 5.1.2 on 2024-12-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
