# Generated by Django 5.1.2 on 2024-12-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_product_identity_remove_product_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='component',
            name='assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='dashboard.assembly'),
        ),
        migrations.AlterField(
            model_name='component',
            name='supplier',
            field=models.CharField(choices=[('Supplier1', 'Supplier1'), ('Supplier2', 'Supplier2')], max_length=50),
        ),
    ]
