# Generated by Django 5.1.2 on 2024-12-18 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_assembly_product_remove_component_assembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='dashboard.product'),
        ),
    ]
