# Generated by Django 5.1.2 on 2024-12-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Finance', 'Finance')], default='Sales', max_length=50),
            preserve_default=False,
        ),
    ]
